# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_days',
            field=models.IntegerField(default=7),
        ),
    ]
